#!/usr/bin/env bash
if [ $# -eq 0 ]; then   # Validation if only argument [0] is passed
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
else
ip_address=$1   # Extract the IP address from the argument [1]
ping -c 5 "$ip_address" # -c <count>   stop after <count> replies
fi