#!/usr/bin/env bash
# Validation if no argument passed
if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi
# Extract the IP address from the argument [1]
ip_address=$1
# -c <count>         stop after <count> replies
ping -c 5 "$ip_address"
