#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument
if [ -z "$1" ]; then    #  verify if the argument [1] is empty
  echo "Usage: $(basename "$0") {IP_ADDRESS}"
  exit 1
fi
ping -c 5 "$1"  # -c <count>   stop after <count> replies
